Repository cognitedata/toolkit, pull requests merged in 2025-06, with the labels that each got.

#1605 Flattened location filter list on API call
  .vscode/launch.json
  cognite_toolkit/_cdf_tk/client/api/location_filters.py
  cognite_toolkit/_cdf_tk/client/api/lookup.py
Labels: risk-review-ongoing, waiting-for-team

#1599 [CDF-24590] 👨‍👩‍👦 Prefer parent over grandparent
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
  tests/data/naughty_project/modules/difficult_graphql/misbehaving_grandparent.GraphQLSchema.graphql
  tests/data/naughty_project/modules/difficult_graphql/misbehaving_grandparent.GraphQLSchema.yaml
  tests/data/naughty_project/modules/difficult_graphql/space.Space.yaml
  tests/test_integration/test_commands/test_dump_data_model.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
Labels: risk-review-ongoing, waiting-for-team

#1606 Use pydantic for transformation validation
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
  cognite_toolkit/_cdf_tk/resource_classes/transformations.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py
Labels: risk-review-ongoing, waiting-for-team

#1624 [prep CDF-24931] 😊 Introduce migrate app
  cdf.toml
  cognite_toolkit/_cdf.py
  cognite_toolkit/_cdf_tk/apps/__init__.py
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
  cognite_toolkit/_cdf_tk/feature_flags.py
Labels: risk-review-ongoing, waiting-for-team

#1618 [prep CDF-24921] 🦈 Add sqlparse
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing, waiting-for-team

#1613 [CDF-24918] ⏱ Toolkit client set-pending-instance-id
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/extended_timeseries.py
  cognite_toolkit/_cdf_tk/client/data_classes/extended_timeseries.py
  cognite_toolkit/_cdf_tk/client/data_classes/pending_instances_ids.py
  tests/test_integration/conftest.py
  tests/test_integration/test_toolkit_client/test_extended_timeseries.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-team

#1626 [CDF-24932] 📊 Added statistics API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/extended_data_modeling.py
  cognite_toolkit/_cdf_tk/client/api/statistics.py
  cognite_toolkit/_cdf_tk/client/data_classes/statistics.py
  cognite_toolkit/_cdf_tk/client/testing.py
  tests/test_integration/test_toolkit_client/test_data_modeling_statistics.py
Labels: risk-review-ongoing, waiting-for-team

#1594 [CDF-24555] 📂 Support dump files
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/commands/dump_data.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_commands/test_dump_data.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1604 [prep CDF-24745] 🧑‍🏭 Schema from view
  cognite_toolkit/_cdf_tk/commands/dump_data.py
  cognite_toolkit/_cdf_tk/utils/table_writers.py
  tests/test_unit/test_cdf_tk/test_utils/test_table_writers.py
Labels: risk-review-ongoing, waiting-for-team

#1628 [CDF-24953] Fix node update
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
  tests/test_integration/test_loaders/test_resource_loaders.py
Labels: risk-review-ongoing, waiting-for-team

#1627 [CDF-24935] 🚅 Robustify and speed up instance writing.
  cognite_toolkit/_cdf_tk/client/_constants.py
  cognite_toolkit/_cdf_tk/client/api/extended_data_modeling.py
  cognite_toolkit/_cdf_tk/client/data_classes/instances.py
  cognite_toolkit/_cdf_tk/client/utils/__init__.py
  cognite_toolkit/_cdf_tk/client/utils/_concurrency.py
  cognite_toolkit/_cdf_tk/client/utils/_http_client.py
  pyproject.toml
  tests/test_integration/test_toolkit_client/test_instances.py
  tests/test_unit/test_cdf_tk/test_client/test_instances.py
  uv.lock
Labels: risk-review-ongoing, waiting-for-risk-review

#1631 ➡Move to partner enablement
  .github/CODEOWNERS
Labels: risk-review-ongoing, waiting-for-risk-review

#1640 [prep CDF-24984] 👷 Refactor migration command
  .gitignore
  cognite_toolkit/_cdf_tk/commands/_migrate/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
  cognite_toolkit/_cdf_tk/commands/_migrate/timeseries.py
  tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py
  tests/test_unit/test_cdf_tk/test_utils/test_collection.py
Labels: waiting-for-risk-review

#1639 [CDF-24990] 😵 Location filename must be unique
  cognite_toolkit/_cdf_tk/builders/_location.py
  tests/data/naughty_project/modules/encoding_issue/data_sets/ds_teste_data_team_1.DataSet.yaml
  tests/data/naughty_project/modules/encoding_issue/transformations/create_data.py
  tests/data/naughty_project/modules/encoding_issue/transformations/my_cp1252.Transformation.yaml
  tests/data/naughty_project/modules/encoding_issue/transformations/my_utf-8.Transformation.yaml
  tests/data/naughty_project/modules/multi_locations/first_location/locations/this.LocationFilter.yaml
  tests/data/naughty_project/modules/multi_locations/second_location/locations/this.LocationFilter.yaml
  tests/test_unit/test_cdf_tk/test_builders/test_location_builder.py
  tests/test_unit/test_cli/test_behavior.py
Labels: risk-review-ongoing, waiting-for-team

#1635 [CDF-24989, CDF-24988] 😅 Group unfortunate diffs
  cognite_toolkit/_builtin_modules/cdf_ingestion/auth/user.Group.yaml
  cognite_toolkit/_builtin_modules/cdf_ingestion/auth/workflow.Group.yaml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_pi/auth/workflow.Group.yaml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/auth/workflow.Group.yaml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/auth/workflow.Group.yaml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/auth/workflow.Group.yaml
  cognite_toolkit/_cdf_tk/resource_classes/capabilities.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_groups.py
  tests/test_unit/test_cdf_tk/test_validation/test_validate_resource_pydantic.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1636 [CDF-24999]🐛 Instance space not required
  cognite_toolkit/_cdf_tk/resource_classes/transformation_destination.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py
Labels: risk-review-ongoing, waiting-for-team

#1615 [CDF-24919] 👷 Fix transformations.preview
  cognite_toolkit/_cdf_tk/client/api/fixed_transformations.py
Labels: risk-review-ongoing, waiting-for-team

#1616 [CDF-24920]➡Transformation targets
  cognite_toolkit/_cdf_tk/commands/_profile.py
Labels: risk-review-ongoing, waiting-for-team

#1648 ⛓Use YAML classes in the validation of assets, events, filemetadata, dataset, and labels
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/data_organization_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/file_loader.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_asset.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_dataset.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_event.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_filemetadata.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_labels.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py
Labels: waiting-for-risk-review

#1642 [CDF-24957] Support for 'labels' in Agent resource
  cognite_toolkit/_cdf_tk/client/data_classes/agents.py
Labels: risk-review-ongoing, waiting-for-team

#1644 [prep CDF-24984] 👷Refactor deploy command Part 1
  cognite_toolkit/_cdf_tk/commands/clean.py
  cognite_toolkit/_cdf_tk/commands/deploy.py
  tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
Labels: waiting-for-risk-review

#1619 [prep CDF-24921] 🦭 Add get_transformation_sources method
  cognite_toolkit/_cdf_tk/utils/cdf.py
  cognite_toolkit/_cdf_tk/utils/sql_parser.py
  tests/test_unit/test_cdf_tk/test_utils/test_cdf.py
Labels: risk-review-ongoing

#1638 [CDF-24874, CDF-24773] 🐞 Pull workflow trigger/transformation
  cognite_toolkit/_cdf_tk/commands/pull.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
  tests/test_unit/test_cli/test_behavior.py
Labels: risk-review-ongoing

#1602 [CDF-24796] Pydantic validation for containers
  cognite_toolkit/_cdf_tk/constants.py
  cognite_toolkit/_cdf_tk/resource_classes/container_field_definitions.py
  cognite_toolkit/_cdf_tk/resource_classes/containers.py
  cognite_toolkit/_cdf_tk/resource_classes/space.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_containers.py
Labels: risk-review-ongoing, waiting-for-team

#1667 Gemini Reviews (on-demand)
  .gemini/config.yaml
Labels: risk-review-ongoing, waiting-for-team

#1653 [prep CDF-25032] 📊 Move aggregators
  cognite_toolkit/_cdf_tk/commands/_profile.py
  cognite_toolkit/_cdf_tk/utils/aggregators.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1654 ⛓Use YAML classes in the validation of function schedule, transformation, schedule, location filters, raw table/DB, security category, space, and 3D
  cognite_toolkit/_builtin_modules/inrobot/default.config.yaml
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/raw_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/three_d_model_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
  cognite_toolkit/_cdf_tk/resource_classes/location.py
  cognite_toolkit/_cdf_tk/resource_classes/raw_database_table.py
  cognite_toolkit/_cdf_tk/tk_warnings/fileread.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_location.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_raw_database_table.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_securitycategories.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_space.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_threedmodels.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_inrobot_common.yaml
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_inrobot_location.yaml
Labels: risk-review-ongoing, waiting-for-risk-review

#1645 [prep CDF-24984] 👷Refactor deploy command part2
  cognite_toolkit/_cdf_tk/apps/_core_app.py
  cognite_toolkit/_cdf_tk/commands/clean.py
  cognite_toolkit/_cdf_tk/commands/deploy.py
  cognite_toolkit/_cdf_tk/data_classes/_deploy_results.py
  cognite_toolkit/_cdf_tk/loaders/_worker.py
  cognite_toolkit/demo/_base.py
  module_upgrade/run_check.py
  tests/test_integration/test_commands/test_deploy.py
  tests/test_integration/test_loaders/test_resource_loaders.py
  tests/test_unit/test_cdf_tk/test_commands/test_deploy.py
  tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_container_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_set_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_view_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_worker.py
  tests/test_unit/test_cli/test_behavior.py
  tests/test_unit/test_cli/test_command_sequences.py
Labels: risk-review-ongoing, waiting-for-team

#1641 [CDF-24881] Function loader requires too broad access
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_worker.py
  tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_worker.py
Labels: risk-review-ongoing, waiting-for-team

#1655 [CDF-25032] 😄Extend aggregators
  cognite_toolkit/_cdf_tk/utils/aggregators.py
  cognite_toolkit/_cdf_tk/utils/sql_parser.py
  tests/test_integration/test_utils/test_aggregators.py
  tests/test_unit/test_cdf_tk/test_utils/test_aggregators.py
Labels: risk-review-ongoing, waiting-for-team

#1674 [prep CDF-24745] 🤵Canvas data classes part 1
  cognite_toolkit/_cdf_tk/client/data_classes/canvas.py
  tests/test_unit/test_cdf_tk/test_client/test_canvas.py
Labels: risk-review-ongoing, waiting-for-team

#1651 [CDF-24890] Search configuration resource type
  cognite_toolkit/_cdf_tk/client/data_classes/search_config.py
  tests/test_unit/test_cdf_tk/test_client/test_search_config.py
Labels: risk-review-ongoing, waiting-for-team

#1659 [CDF-25010] 🪨Datapoint subscription with timeSeriesIds or InstanceIds
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
  cognite_toolkit/_cdf_tk/utils/text.py
  tests/test_integration/conftest.py
  tests/test_integration/test_loaders/test_resource_loaders.py
  tests/test_unit/test_cdf_tk/test_utils/test_text.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1670 [CDF-24819] 🧑‍🏭 Added workflow YAML
  cognite_toolkit/_cdf_tk/resource_classes/workflow.py
  tests/data/complete_org/config.dev.yaml
  tests/data/complete_org/modules/my_example_module/workflows/first.Workflow.yaml
  tests/data/complete_org/modules/my_example_module/workflows/first.WorkflowTrigger.yaml
  tests/data/complete_org/modules/my_example_module/workflows/first.WorkflowVersion.yaml
  tests/test_unit/test_cdf_tk/test_resource_classes/test_workflow.py
Labels: risk-review-ongoing, waiting-for-team

#1692 💣Fix fragile tests
  tests/test_integration/test_commands/test_migrate_timeseries.py
Labels: risk-review-ongoing, waiting-for-team

#1665 [CDF-25070] ⛓️‍💥 Unlink timeseries
  cognite_toolkit/_cdf_tk/client/api/extended_timeseries.py
  tests/auth_utils.py
  tests/test_integration/test_toolkit_client/test_extended_timeseries.py
  tests/test_unit/test_cdf_tk/test_client/conftest.py
  tests/test_unit/test_cdf_tk/test_client/test_extended_timeseries.py
  tests/test_unit/test_cdf_tk/test_client/test_instances.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1669 [prep CDF-24984] 👷Refactor deploy part 3
  cognite_toolkit/_cdf_tk/commands/_migrate/prepare.py
  cognite_toolkit/_cdf_tk/commands/deploy.py
  cognite_toolkit/_cdf_tk/loaders/_worker.py
  tests/test_integration/test_commands/test_deploy.py
  tests/test_integration/test_loaders/test_resource_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_container_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_set_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_view_loader.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-risk-review

#1687 🦾Fix helper
  tests/auth_utils.py
Labels: risk-review-ongoing, waiting-for-team
