Repository cognitedata/toolkit, pull requests merged in 2025-04, with the labels that each got.

#1522 [CDF-23633] 🪲 Failed lookup not deployed asset
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/classic_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/timeseries_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_classic_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_time_series_loader.py
Labels: risk-review-ongoing

#1526 [CDF-24437] Agent CRUD Alpha support
  cdf.toml
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/agents/agents.py
  cognite_toolkit/_cdf_tk/client/api/agents/api.py
  cognite_toolkit/_cdf_tk/client/data_classes/agent_tools.py
  cognite_toolkit/_cdf_tk/client/data_classes/agents.py
  cognite_toolkit/_cdf_tk/feature_flags.py
  cognite_toolkit/_cdf_tk/loaders/__init__.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/__init__.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
  tests/test_unit/test_cdf_tk/test_client/test_agent.py
  tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
Labels: risk-review-ongoing

#1531 [CDF-24461] 🙃 Support Infield Configuration Part 1
  cognite_toolkit/_cdf_tk/client/data_classes/apm_config_v1.py
  tests/test_unit/test_cdf_tk/test_client/test_apm_config_v1.py
Labels: risk-review-ongoing, risk-review-done

#1527 [CDF-24416] 🔩 Dump global data model no longer skips views, containers, and spaces
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  tests/test_integration/test_commands/test_dump_data_model.py
Labels: risk-review-done

#1532 [CDF-24461] 🧁 Support Infield Configuration Part 2
  cdf.toml
  cognite_toolkit/_cdf_tk/client/data_classes/apm_config_v1.py
  cognite_toolkit/_cdf_tk/feature_flags.py
  cognite_toolkit/_cdf_tk/loaders/__init__.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/__init__.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/fieldops_loaders.py
  tests/data/complete_org_alpha_flags/modules/my_example_module/cdf_applications/my_location.InfieldV1.yaml
  tests/test_unit/test_cdf_tk/test_loaders/test_base_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_fieldops_loaders.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml
  tests/test_unit/utils.py
Labels: risk-review-done

#1536 hotfix for extraction pipelines bug/overuse
  cognite_toolkit/_builtin_modules/bootcamp/ice_cream_api/functions/icapi_datapoints_extractor/handler.py
Labels: risk-review-ongoing

#1533 [CDF-24483] Added 'usedFor' variable to make sure 3d data model is correct
  cognite_toolkit/_builtin_modules/models/cdf_scene/data_models/containers/scene_Cdf3dRevisionProperties.Container.yaml
  cognite_toolkit/_builtin_modules/models/cdf_scene/data_models/containers/scene_Image360CollectionProperties.Container.yaml
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_scene.yaml
Labels: risk-review-ongoing

#1539 [CDF-24509] 🖋 Encoding issue
  cdf.toml
  cognite_toolkit/_cdf_tk/builders/_transformation.py
  cognite_toolkit/_cdf_tk/cdf_toml.py
  cognite_toolkit/_cdf_tk/commands/build_cmd.py
  cognite_toolkit/_cdf_tk/constants.py
  cognite_toolkit/_cdf_tk/loaders/_base_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_data_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/extraction_pipeline_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/fieldops_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
  cognite_toolkit/_cdf_tk/utils/file.py
  tests/data/__init__.py
  tests/data/naughty_project/README.md
  tests/data/naughty_project/cdf.toml
  tests/data/naughty_project/modules/encoding_issue/case/data_sets/ds_teste_data_team_1.DataSet.yaml
  tests/data/naughty_project/modules/encoding_issue/case/transformations/create_data.py
  tests/data/naughty_project/modules/encoding_issue/case/transformations/my_cp1252.Transformation.yaml
  tests/data/naughty_project/modules/encoding_issue/case/transformations/my_utf-8.Transformation.yaml
  tests/test_unit/test_cli/test_behavior.py
Labels: risk-review-ongoing, waiting-for-team

#1540 [CDF-24561] 👷 Introduce Toolkit Resource Classes
  cognite_toolkit/_cdf_tk/resource_classes/__init__.py
  cognite_toolkit/_cdf_tk/resource_classes/base.py
  cognite_toolkit/_cdf_tk/resource_classes/timeseries.py
  pyproject.toml
  tests/test_unit/test_cdf_tk/test_resource_classes/__init__.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_timeseries.py
  uv.lock
Labels: waiting-for-risk-review

#1544 [CDF-24586] 🧑‍🔧 Deploying more than 100 workflows
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_workflow_loaders.py
Labels: risk-review-ongoing, waiting-for-team

#1549 😐 Fix git ignore
  .gitignore
Labels: waiting-for-risk-review
