Repository cognitedata/toolkit, pull requests merged in 2025-05, with the labels that each got.

#1547 [CDF-4571] Pydantic Validation for DataSet
  cognite_toolkit/_cdf_tk/resource_classes/__init__.py
  cognite_toolkit/_cdf_tk/resource_classes/dataset.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_dataset.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_timeseries.py
  tests/test_unit/utils.py
Labels: risk-review-ongoing, waiting-for-team

#1551 [CDF-24572] Pydantic Validation for Assets
  cognite_toolkit/_cdf_tk/resource_classes/asset.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_asset.py
Labels: risk-review-ongoing, waiting-for-team

#1554 [CDF-24575] Pydantic Validation for 3D models
  cognite_toolkit/_cdf_tk/resource_classes/threedmodels.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_threedmodels.py
Labels: risk-review-ongoing, waiting-for-team

#1556 [CDF-24577] Pydantic Validation for Labels
  cognite_toolkit/_cdf_tk/resource_classes/labels.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_labels.py
Labels: risk-review-ongoing, waiting-for-team

#1552 [CDF-24573] Pydantic Validation for Events
  cognite_toolkit/_cdf_tk/resource_classes/event.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_event.py
Labels: risk-review-ongoing, waiting-for-team

#1553 [CDF-24574] Pydantic Validation for Spaces
  cognite_toolkit/_cdf_tk/resource_classes/space.py
  tests/data/complete_org/config.dev.yaml
  tests/data/complete_org/modules/my_file_expand_module/data_models/file.Space.yaml
  tests/data/complete_org/modules/my_file_expand_module/files/my.CogniteFile.yaml
  tests/test_unit/test_cdf_tk/test_resource_classes/test_space.py
Labels: risk-review-ongoing, waiting-for-team

#1558 [CDF-24579] Pydantic Validation for Raw Database and Table
  cognite_toolkit/_cdf_tk/resource_classes/raw_database_table.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_raw_database_table.py
Labels: risk-review-ongoing, waiting-for-team

#1561 [CDF-24651] 👷 Fix template
  cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/functions/contextualization_p_and_id_annotater/handler.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_p_and_id_parser.yaml
Labels: risk-review-ongoing, waiting-for-team

#1557 [CDF-24578] Pydantic Validation for FileMetadata
  cognite_toolkit/_cdf_tk/resource_classes/filemetadata.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_filemetadata.py
Labels: risk-review-ongoing, waiting-for-team

#1560 [CDF-23856] 🚶 Pydantic Group
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/auth_loaders.py
  cognite_toolkit/_cdf_tk/resource_classes/__init__.py
  cognite_toolkit/_cdf_tk/resource_classes/capabilities.py
  cognite_toolkit/_cdf_tk/resource_classes/groups.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_commands/test_build.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_groups.py
  tests/test_unit/test_cdf_tk/test_validation/test_validate_resource_pydantic.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-risk-review

#1559 [CDF-24580] Pydantic Validation for Functions
  cognite_toolkit/_cdf_tk/resource_classes/functions.py
  tests/data/complete_org/modules/my_example_module/functions/first.function.yaml
  tests/test_unit/test_cdf_tk/test_resource_classes/test_functions.py
Labels: risk-review-ongoing, waiting-for-team

#1562 🪟View detected as changed.
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/datamodel_loaders.py
  tests/data/complete_org/modules/my_example_module/data_models/child.View.yaml
  tests/data/complete_org/modules/my_example_module/data_models/description.Container.yaml
  tests/data/complete_org/modules/my_example_module/data_models/name.Container.yaml
  tests/data/complete_org/modules/my_example_module/data_models/parent.View.yaml
  tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-risk-review

#1569 Allow upper case
  dev.py
  tests/test_unit/test_toolkit_release_process.py
Labels: risk-review-ongoing, waiting-for-team

#1567 ⛏Fix failing CI build demo
  .github/workflows/demo.yml
  demo/config.demo.yaml
  demo/postproc.py
Labels: waiting-for-risk-review

#1572 [CDF-24719] 🐛 Fix id scope extractionPipelinesAcl
  cognite_toolkit/_cdf_tk/resource_classes/__init__.py
  cognite_toolkit/_cdf_tk/resource_classes/capabilities.py
  cognite_toolkit/_cdf_tk/validation.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_capabilities.py
  tests/test_unit/test_cdf_tk/test_validation/test_validate_resource_pydantic.py
Labels: risk-review-ongoing, waiting-for-team

#1568 Updates to GitHub Action support
  cognite_toolkit/_repo_files/GitHub/.github/workflows/dry-run.yaml
  dev.py
Labels: risk-review-ongoing, waiting-for-team

#1576 Updating pydantic
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing

#1577 Outdated path in dev.py script
  dev.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1579 Making .env override default True
  cognite_toolkit/_cdf_tk/apps/_core_app.py
Labels: risk-review-ongoing, waiting-for-team

#1543 [CDF-24563] Topological sort to fix dependencies between location filters
  .vscode/launch.json
  cognite_toolkit/_cdf_tk/builders/__init__.py
  cognite_toolkit/_cdf_tk/builders/_location.py
  cognite_toolkit/_cdf_tk/client/api/lookup.py
  cognite_toolkit/_cdf_tk/client/data_classes/location_filters.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
  tests/data/complete_org/modules/my_example_module/locations/nested.LocationFilter.yaml
  tests/test_integration/test_commands/test_deploy.py
  tests/test_unit/test_cdf_tk/test_builders/test_location_builder.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml
  tests/test_unit/utils.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1571 [prep CDF-24554] Prep dump events
  cdf.toml
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/feature_flags.py
  tests/test_integration/test_commands/test_dump_data_model.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1583 Allow renovate PRs
  dev.py
  tests/test_unit/test_toolkit_release_process.py
Labels: risk-review-ongoing, waiting-for-team

#1563 [CDF-24581] Pydantic Validation for Function schedules
  .gitignore
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
  cognite_toolkit/_cdf_tk/resource_classes/function_schedule.py
  tests/data/complete_org/modules/my_example_module/functions/first.schedule.yaml
  tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_functionschedule.py
  tests/test_unit/utils.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1575 [CDF-24583] Pydantic Validation for location
  cognite_toolkit/_cdf_tk/resource_classes/location.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_location.py
Labels: risk-review-ongoing, waiting-for-team

#1574 [CDF-24582] Pydantic Validation for transformations
  cognite_toolkit/_cdf_tk/resource_classes/transformation_destination.py
  cognite_toolkit/_cdf_tk/resource_classes/transformations.py
  tests/data/complete_org/modules/my_example_module/transformations/first.transformation.yaml
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org.yaml
Labels: risk-review-ongoing, waiting-for-team

#1597 Expose new yaml classe in module
  cognite_toolkit/_cdf_tk/resource_classes/__init__.py
  cognite_toolkit/_cdf_tk/resource_classes/securitycategories.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_securitycategories.py
Labels: risk-review-ongoing, waiting-for-team
