Repository cognitedata/toolkit, pull requests merged in 2025-07, with the labels that each got.

#1675 [prep CDF-24745] 🤵Canvas data classes part 2
  cognite_toolkit/_cdf_tk/client/data_classes/canvas.py
  tests/test_unit/test_cdf_tk/test_client/test_canvas.py
Labels: risk-review-ongoing, waiting-for-team

#1676 [prep CDF-24745] 🤵Canvas API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/canvas.py
  cognite_toolkit/_cdf_tk/client/data_classes/canvas.py
  cognite_toolkit/_cdf_tk/client/testing.py
  tests/test_unit/test_cdf_tk/test_client/test_canvas.py
Labels: risk-review-ongoing, waiting-for-team

#1673 [CDF-24982] 🧑‍🎨 Interactive select canvas
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
  cognite_toolkit/_cdf_tk/commands/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/canvas.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-team

#1662 [CDF-24991] 🌍 Asset profiler try 2
  cognite_toolkit/_cdf_tk/apps/_profile_app.py
  cognite_toolkit/_cdf_tk/client/data_classes/raw.py
  cognite_toolkit/_cdf_tk/commands/__init__.py
  cognite_toolkit/_cdf_tk/commands/_profile.py
  tests/test_integration/test_commands/test_profile.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1650 [CDF-25024] Package toml restructure
  LIBRARIES.md
  cognite_toolkit/_builtin_modules/bootcamp/ice_cream_api/module.toml
  cognite_toolkit/_builtin_modules/bootcamp/module.toml
  cognite_toolkit/_builtin_modules/bootcamp/use_cases/oee/module.toml
  cognite_toolkit/_builtin_modules/cdf_common/module.toml
  cognite_toolkit/_builtin_modules/cdf_ingestion/module.toml
  cognite_toolkit/_builtin_modules/common/cdf_apm_base/module.toml
  cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/module.toml
  cognite_toolkit/_builtin_modules/contextualization/cdf_connection_sql/module.toml
  cognite_toolkit/_builtin_modules/contextualization/cdf_entity_matching/module.toml
  cognite_toolkit/_builtin_modules/contextualization/cdf_p_and_id_parser/module.toml
  cognite_toolkit/_builtin_modules/custom/my_module/module.toml
  cognite_toolkit/_builtin_modules/industrial_tools/cdf_location_filter_asset_centric/module.toml
  cognite_toolkit/_builtin_modules/industrial_tools/cdf_location_filter_datamodel_based/module.toml
  cognite_toolkit/_builtin_modules/industrial_tools/cdf_search/module.toml
  cognite_toolkit/_builtin_modules/infield/cdf_infield_common/module.toml
  cognite_toolkit/_builtin_modules/infield/cdf_infield_location/module.toml
  cognite_toolkit/_builtin_modules/infield/cdf_infield_second_location/module.toml
  cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_common/module.toml
  cognite_toolkit/_builtin_modules/inrobot/cdf_inrobot_location/module.toml
  cognite_toolkit/_builtin_modules/models/cdf_cdm_extension/module.toml
  cognite_toolkit/_builtin_modules/models/cdf_cdm_extension_full/module.toml
  cognite_toolkit/_builtin_modules/models/cdf_process_industry_extension/module.toml
  cognite_toolkit/_builtin_modules/models/cdf_process_industry_extension_full/module.toml
  cognite_toolkit/_builtin_modules/models/cdf_scene/module.toml
  cognite_toolkit/_builtin_modules/packages.toml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_pi/module.toml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_assets/module.toml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sap_events/module.toml
  cognite_toolkit/_builtin_modules/sourcesystem/cdf_sharepoint/module.toml
  cognite_toolkit/_cdf_tk/data_classes/_module_directories.py
  cognite_toolkit/_cdf_tk/data_classes/_module_toml.py
  cognite_toolkit/_cdf_tk/data_classes/_packages.py
  tests/test_unit/test_cdf_tk/test_commands/test_modules.py
  tests/test_unit/test_cdf_tk/test_data_classes/test_packages.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_common.yaml
Labels: risk-review-ongoing, waiting-for-risk-review

#1708 Temporarily skip test
  tests/test_integration/test_commands/test_migrate_prepare.py
Labels: waiting-for-risk-review

#1666 Search Configuration API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/search_config.py
  tests/test_integration/test_toolkit_client/test_search_config.py
Labels: risk-review-ongoing, waiting-for-team

#1686 [prep CDF-24982] 🚃 Migration API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/migration.py
  cognite_toolkit/_cdf_tk/client/data_classes/migration.py
  cognite_toolkit/_cdf_tk/client/testing.py
  tests/test_integration/test_toolkit_client/test_migration.py
Labels: risk-review-ongoing, waiting-for-team

#1663 [CDF-24921] 👻 Raw profiler try 2
  .vscode/settings.json
  cognite_toolkit/_cdf_tk/apps/_profile_app.py
  cognite_toolkit/_cdf_tk/commands/__init__.py
  cognite_toolkit/_cdf_tk/commands/_profile.py
  tests/test_integration/test_commands/test_profile.py
Labels: risk-review-ongoing, waiting-for-team

#1705 [CDF-24792] 🐛 Correct error message
  cognite_toolkit/_cdf_tk/commands/_migrate/prepare.py
  cognite_toolkit/_cdf_tk/commands/clean.py
  cognite_toolkit/_cdf_tk/commands/deploy.py
  cognite_toolkit/_cdf_tk/loaders/_worker.py
  tests/test_integration/test_commands/test_deploy.py
  tests/test_integration/test_loaders/test_resource_loaders.py
  tests/test_unit/test_cdf_tk/test_commands/test_deploy.py
  tests/test_unit/test_cdf_tk/test_loaders/test_container_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_model_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_data_set_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_extraction_pipeline_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_function_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_group_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_view_loader.py
  tests/test_unit/test_cdf_tk/test_loaders/test_worker.py
Labels: risk-review-ongoing, waiting-for-team

#1714 [CDF-25165] ⛓Fix 404 links
  cognite_toolkit/_cdf_tk/constants.py
  tests/test_unit/test_cdf_tk/tests_constants.py
Labels: waiting-for-risk-review

#1689 [prep CDF-24982] 🫅 Canvas industrial CRUD API
  cognite_toolkit/_cdf_tk/client/api/canvas.py
  tests/test_integration/test_toolkit_client/test_canvas.py
Labels: risk-review-ongoing, waiting-for-team

#1726 [CDF-25147]🐛 Bug in row count
  cognite_toolkit/_cdf_tk/utils/cdf.py
  tests/test_integration/test_utils/test_cdf.py
Labels: risk-review-ongoing, waiting-for-team

#1734 [CDF-25033] 🏗 Refactor interactive select
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/utils/aggregators.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-team

#1723 [prep CDF-25149] 🔨 Introduce scope logic
  cognite_toolkit/_cdf_tk/client/data_classes/capabilities.py
  tests/test_unit/test_cdf_tk/test_client/test_capabilities.py
Labels: risk-review-ongoing, waiting-for-team

#1738 🧱 Move out JSON type
  cognite_toolkit/_cdf_tk/utils/table_writers.py
  cognite_toolkit/_cdf_tk/utils/useful_types.py
Labels: waiting-for-team

#1731 [CDF-25064] 🦗 Fix location filter deploy order
  cognite_toolkit/_cdf_tk/builders/_location.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
  tests/test_unit/test_cdf_tk/test_loaders/test_locations_loader.py
  tests/test_unit/test_cli/test_behavior.py
Labels: risk-review-ongoing, waiting-for-team

#1703 [CDF-25149] Get Scope
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/token.py
  cognite_toolkit/_cdf_tk/client/testing.py
  tests/test_unit/test_cdf_tk/test_client/test_token_api.py
Labels: risk-review-ongoing, waiting-for-team

#1710 [prep CDF-25018] 📋 Support set-pending-ids for files
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/extended_files.py
  cognite_toolkit/_cdf_tk/client/data_classes/extended_filemetadata.py
  tests/test_integration/test_toolkit_client/conftest.py
  tests/test_integration/test_toolkit_client/test_extended_files.py
  tests/test_integration/test_toolkit_client/test_extended_timeseries.py
  tests/test_unit/test_cdf_tk/test_client/test_extended_filemetadata.py
Labels: risk-review-ongoing, waiting-for-team

#1735 [CDF-25194] 👷‍♂️ Update instance source API
  cognite_toolkit/_cdf_tk/client/api/migration.py
  cognite_toolkit/_cdf_tk/client/data_classes/migration.py
  cognite_toolkit/_cdf_tk/client/testing.py
  tests/test_integration/test_toolkit_client/test_migration.py
Labels: risk-review-ongoing, waiting-for-team

#1757 [prep CDF-25251] 🧑‍🎓Standardize Search client API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/lookup.py
  cognite_toolkit/_cdf_tk/client/api/search.py
  cognite_toolkit/_cdf_tk/client/data_classes/search_config.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
  tests/test_integration/test_toolkit_client/test_locations.py
  tests/test_integration/test_toolkit_client/test_search_config.py
  tests/test_unit/approval_client/config.py
  tests/test_unit/test_cdf_tk/test_commands/test_dump_resource.py
Labels: risk-review-ongoing, waiting-for-team

#1765 [CDF-25263] 💣 Bom character
  cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
  tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py
Labels: risk-review-ongoing, waiting-for-team

#1741 [CDF-25245] 🐛 Listed FROM blocks in SQL queries
  cognite_toolkit/_cdf_tk/utils/sql_parser.py
  tests/test_unit/test_cdf_tk/test_utils/test_cdf.py
Labels: risk-review-ongoing, waiting-for-team

#1763 [CDF-25262] ⬆ Update agents API
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/agents/agents.py
  cognite_toolkit/_cdf_tk/client/api/agents/api.py
  cognite_toolkit/_cdf_tk/client/data_classes/agent_tools.py
  cognite_toolkit/_cdf_tk/client/data_classes/agents.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
  pyproject.toml
  tests/test_unit/test_cdf_tk/test_client/test_agent.py
  uv.lock
Labels: risk-review-ongoing, waiting-for-risk-review

#1769 [CDF-25286] 🦾 Improve producer worker
  cognite_toolkit/_cdf_tk/commands/dump_data.py
  cognite_toolkit/_cdf_tk/utils/producer_worker.py
  tests/test_unit/test_cdf_tk/test_utils/test_producer_worker.py
Labels: risk-review-ongoing, waiting-for-team

#1781 [CDF-24838] Update Cognite-SDK to 7.77.0
  cognite_toolkit/_cdf_tk/client/api/extended_data_modeling.py
  cognite_toolkit/_cdf_tk/client/api/statistics.py
  cognite_toolkit/_cdf_tk/client/data_classes/statistics.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/_migrate/base.py
  pyproject.toml
  tests/test_integration/test_toolkit_client/test_data_modeling_statistics.py
  tests/test_unit/test_cdf_tk/test_commands/test_migrate.py
  uv.lock
Labels: risk-review-ongoing, waiting-for-team

#1739 [CDF-25192] 👮 Respect frequency of Raw Row count
  cognite_toolkit/_cdf_tk/exceptions.py
  cognite_toolkit/_cdf_tk/utils/cdf.py
  pyproject.toml
  tests/test_integration/test_utils/test_cdf.py
  uv.lock
Labels: risk-review-ongoing, waiting-for-risk-review

#1717 [CDF-25018] ➡ cdf migrate files
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
  cognite_toolkit/_cdf_tk/client/data_classes/extended_filemetdata.py
  cognite_toolkit/_cdf_tk/commands/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/files.py
  tests/test_integration/test_commands/test_migrate_files.py
Labels: risk-review-ongoing, waiting-for-team

#1748 [prep CDF-25249] 💦 Support filtering for label listing
  cognite_toolkit/_cdf_tk/utils/cdf.py
  tests/test_integration/test_utils/test_cdf.py
  tests/test_unit/test_cdf_tk/test_commands/test_dump_data.py
Labels: risk-review-ongoing, waiting-for-team

#1743 [CDF-25193] 🧑‍🎨 cdf profile nicer terminal output
  cognite_toolkit/_cdf_tk/commands/_profile.py
  tests/test_unit/test_cdf_tk/test_commands/test_profile.py
Labels: risk-review-ongoing, waiting-for-team

#1742 [CDF-25241] 🦾 Interactive selection cdf profile raw/transformations
  cognite_toolkit/_cdf_tk/apps/_profile_app.py
  cognite_toolkit/_cdf_tk/commands/_profile.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  cognite_toolkit/_cdf_tk/utils/useful_types.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1770 [CDF-25151] 😆 Data modeling interactive select
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-team

#1755 [CDF-24982] 🧑‍🎨➡ Canvas migration
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
  cognite_toolkit/_cdf_tk/client/data_classes/canvas.py
  cognite_toolkit/_cdf_tk/client/data_classes/migration.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/_migrate/base.py
  cognite_toolkit/_cdf_tk/commands/_migrate/canvas.py
  tests/test_unit/test_cdf_tk/test_commands/test_migrate_canvas.py
Labels: risk-review-ongoing, waiting-for-team

#1777 [CDF-25285] 🦿Convert asset-centric properties to container properties Part 1
  cognite_toolkit/_cdf_tk/utils/dtype_conversion.py
  pyproject.toml
  tests/test_unit/test_cdf_tk/test_utils/test_dtype_conversion.py
  uv.lock
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-risk-review

#1745 [CDF-25247] 🦋 Refactor interactive selection asset centric
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_utils/test_aggregators.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-team

#1801 [CDF-25341] 🐛 Fix sanitize sheet title
  cognite_toolkit/_cdf_tk/commands/_profile.py
  cognite_toolkit/_cdf_tk/utils/text.py
  tests/test_unit/test_cdf_tk/test_utils/test_text.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1810 [CDF-25385] 😁 Use upsert instead of delete - create
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/workflow_loaders.py
Labels: risk-review-ongoing, waiting-for-risk-review
