Repository cognitedata/toolkit, pull requests merged in 2025-09, with the labels that each got.

#1893 😄Update ruff id in pre-commit
  .pre-commit-config.yaml
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
Labels: risk-review-ongoing, waiting-for-team

#1887 🐛 Fix: flaky test
  tests/test_integration/test_toolkit_client/test_extended_files.py
Labels: risk-review-ongoing, waiting-for-team

#1869 [CDF-25604]🏗 Introducing migration issues
  cognite_toolkit/_cdf_tk/commands/_migrate/issues.py
  tests/test_unit/test_cdf_tk/test_commands/test_migration.py
Labels: risk-review-ongoing, waiting-for-team

#1876 [prep CDF-25371] 🧑‍🎓 Instance list
  cognite_toolkit/_cdf_tk/client/data_classes/instances.py
  tests/test_unit/test_cdf_tk/test_client/test_instances.py
Labels: risk-review-ongoing, waiting-for-team

#1868 [CDF-25605] 👷Refactor migration base
  cognite_toolkit/_cdf_tk/commands/_migrate/assets.py
  cognite_toolkit/_cdf_tk/commands/_migrate/base.py
  cognite_toolkit/_cdf_tk/commands/_migrate/canvas.py
  cognite_toolkit/_cdf_tk/commands/_migrate/data_model.py
  cognite_toolkit/_cdf_tk/commands/_migrate/files.py
  cognite_toolkit/_cdf_tk/commands/_migrate/timeseries.py
  tests/test_unit/test_cdf_tk/test_commands/test_migrate.py
  tests/test_unit/test_cdf_tk/test_commands/test_migrate_canvas.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1878 [prep CDF-25553] 👷‍♂️ Validate file access
  cognite_toolkit/_cdf_tk/utils/validate_access.py
  tests/test_unit/test_cdf_tk/test_utils/test_validate_access.py
Labels: risk-review-ongoing, waiting-for-team

#1875 [CDF-25371] Instance IO implementation (download part)
  cognite_toolkit/_cdf_tk/storageio/__init__.py
  cognite_toolkit/_cdf_tk/storageio/_instances.py
  cognite_toolkit/_cdf_tk/storageio/_selectors.py
  tests/test_unit/test_cdf_tk/test_storageio/test_instance_io.py
Labels: risk-review-ongoing, waiting-for-team

#1888 [CDF-25640] 😄Chart StorageIO
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/storageio/__init__.py
  cognite_toolkit/_cdf_tk/storageio/_applications.py
  cognite_toolkit/_cdf_tk/storageio/_selectors.py
  tests/test_unit/test_cdf_tk/test_client/test_client_config.py
  tests/test_unit/test_cdf_tk/test_storageio/test_applications.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1884 [CDF-25550] ⬆ Support upload assets
  cognite_toolkit/_cdf_tk/apps/_upload_app.py
  cognite_toolkit/_cdf_tk/commands/_upload.py
  cognite_toolkit/_cdf_tk/storageio/_asset_centric.py
  tests/test_unit/test_cdf_tk/test_storageio/test_asset_centric.py
Labels: risk-review-ongoing, waiting-for-team

#1860 [prep CDF-25295] 🫠 Introduce new columns
  cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
  cognite_toolkit/_cdf_tk/utils/fileio/_compression.py
  tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py
  tests/test_unit/test_cdf_tk/test_utils/test_collection.py
  tests/test_unit/test_cdf_tk/test_utils/test_fileio.py
Labels: risk-review-ongoing, waiting-for-team

#1870 [CDF-25603] 😆 Asset-Centric to instance conversion
  cognite_toolkit/_cdf_tk/client/data_classes/migration.py
  cognite_toolkit/_cdf_tk/commands/_migrate/base.py
  cognite_toolkit/_cdf_tk/commands/_migrate/conversion.py
  cognite_toolkit/_cdf_tk/commands/_migrate/issues.py
  tests/test_unit/test_cdf_tk/test_commands/test_migration.py
Labels: risk-review-ongoing, waiting-for-team

#1897 [CDF-24821] 📋 Yaml class workflow trigger
  cognite_toolkit/_cdf_tk/resource_classes/authentication.py
  cognite_toolkit/_cdf_tk/resource_classes/function_schedule.py
  cognite_toolkit/_cdf_tk/resource_classes/transformations.py
  cognite_toolkit/_cdf_tk/resource_classes/workflow_trigger.py
  tests/data/complete_org/modules/my_example_module/workflows/first.WorkflowTrigger.yaml
  tests/test_unit/test_cdf_tk/test_resource_classes/test_functionschedule.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformations.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_workflow_triggers.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1880 [CDF-25626] Robust stopping
  cognite_toolkit/_cdf_tk/commands/_migrate/assets.py
  cognite_toolkit/_cdf_tk/commands/_purge.py
  cognite_toolkit/_cdf_tk/commands/_upload.py
  cognite_toolkit/_cdf_tk/commands/dump_data.py
  cognite_toolkit/_cdf_tk/storageio/_raw.py
  cognite_toolkit/_cdf_tk/utils/producer_worker.py
  tests/test_unit/test_cdf_tk/test_utils/test_producer_worker.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-risk-review

#1906 [CDF-24818] 🍨 Datapoint subscription YAML class
  cognite_toolkit/_cdf_tk/resource_classes/datapoint_subscription.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_datapoint_subscription_yaml.py
Labels: risk-review-ongoing, waiting-for-team

#1911 [CDF-25666] 🗺 Data mapper interface
  cognite_toolkit/_cdf_tk/commands/_migrate/data_mapper.py
Labels: risk-review-ongoing, waiting-for-team

#1909 [CDF-24802] 🥟 Added ExtractionPipelineYAML
  cognite_toolkit/_cdf_tk/resource_classes/extraction_pipeline.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_extraction_pipeline.py
Labels: risk-review-ongoing, waiting-for-team

#1913 [CDF-25676] 🤨Remove upper bound packaging
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing, waiting-for-team

#1908 [CDF-24816] Transformation notification yaml
  cognite_toolkit/_cdf_tk/resource_classes/transformation_notification.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_transformation_notification.py
Labels: risk-review-ongoing, waiting-for-team

#1927 🐛Fix documentation
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
Labels: waiting-for-risk-review

#1918 [CDF-25685] 🤗 Streamlit app entrypoint no longer required in metadata
  cognite_toolkit/_cdf_tk/client/data_classes/streamlit_.py
Labels: risk-review-ongoing, waiting-for-team

#1877 [prep CDF-25553] 👷 Refactor purge instances
  cognite_toolkit/_cdf_tk/apps/_purge.py
  cognite_toolkit/_cdf_tk/commands/_purge.py
  cognite_toolkit/_cdf_tk/storageio/_selectors.py
  tests/test_unit/conftest.py
  tests/test_unit/test_cdf_tk/test_commands/test_purge.py
Labels: risk-review-ongoing, waiting-for-team

#1929 [prep CDF-25015] 🕵 Added validation for asset access
  cognite_toolkit/_cdf_tk/utils/validate_access.py
  tests/test_unit/test_cdf_tk/test_utils/test_validate_access.py
Labels: risk-review-ongoing, waiting-for-team

#1933 [CDF-24807] 🎍 Hosted Extractor Mapping YAML
  cognite_toolkit/_cdf_tk/resource_classes/hosted_extractor_mapping.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_hosted_extractor_mapping.py
Labels: risk-review-ongoing, waiting-for-team

#1932 [CDF-24817] 🎏 StreamlitYAML
  cognite_toolkit/_cdf_tk/resource_classes/streamlit_.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_streamlit.py
Labels: risk-review-ongoing, waiting-for-team

#1953 [CDF-25736] 👇Serialization HTTPMessage
  cognite_toolkit/_cdf_tk/utils/http_client/_data_classes.py
  tests/test_unit/test_cdf_tk/test_utils/test_http_client.py
  tests/test_unit/utils.py
Labels: risk-review-ongoing, waiting-for-team

#1961 fix: Update the "Switch principal" error message
  cognite_toolkit/_cdf_tk/commands/auth.py
Labels: risk-review-ongoing, waiting-for-team

#1965 [CDF-25742] α Support setting alpha flag
  cognite_toolkit/_cdf_tk/utils/http_client/_client.py
  cognite_toolkit/_cdf_tk/utils/http_client/_data_classes.py
  tests/test_unit/test_cdf_tk/test_utils/test_http_client.py
Labels: risk-review-ongoing, waiting-for-team

#1974 [prep CDF-25015] 🧵 Thread safe dict
  cognite_toolkit/_cdf_tk/utils/thread_safe_dict.py
  cognite_toolkit/_cdf_tk/utils/useful_types.py
  tests/test_unit/test_cdf_tk/test_utils/test_thread_safe_dict.py
Labels: risk-review-ongoing, waiting-for-team

#1984 🚨Warning message on purge
  cognite_toolkit/_cdf_tk/commands/_purge.py
Labels: waiting-for-risk-review

#1981 🐛 API spec for extraction pipeline
  cognite_toolkit/_cdf_tk/resource_classes/extraction_pipeline.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_extraction_pipeline.py
Labels: risk-review-ongoing

#1943 [CDF-25015, CDF-25296, CDF-25295] 🏭 Migration assets
  cognite_toolkit/_cdf_tk/commands/_migrate/adapter.py
  cognite_toolkit/_cdf_tk/commands/_migrate/command.py
  cognite_toolkit/_cdf_tk/utils/progress_tracker.py
  tests/test_unit/test_cdf_tk/test_commands/test_migration_cmd/test_command.py
Labels: risk-review-ongoing, waiting-for-team

#1949 [CDF-24801] Pydantic class for Edge
  cognite_toolkit/_cdf_tk/constants.py
  cognite_toolkit/_cdf_tk/resource_classes/instance.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_instance.py
Labels: risk-review-ongoing, waiting-for-team

#1970 [CDF-25745] 👮 Add request tracker
  cognite_toolkit/_cdf_tk/utils/http_client/_client.py
  cognite_toolkit/_cdf_tk/utils/http_client/_data_classes.py
  cognite_toolkit/_cdf_tk/utils/http_client/_tracker.py
  tests/test_unit/test_cdf_tk/test_utils/test_http_client.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1976 [CDF-25751] 🫅 Extending space selection
  cognite_toolkit/_cdf_tk/apps/_purge.py
  cognite_toolkit/_cdf_tk/utils/interactive_select.py
  tests/test_unit/test_cdf_tk/test_utils/test_interactive_select.py
Labels: risk-review-ongoing, waiting-for-team

#1983 [CDF-25601] 🤩Replace client
  cognite_toolkit/_cdf_tk/commands/_purge.py
  tests/test_integration/test_commands/test_purge.py
  tests/test_unit/test_cdf_tk/test_commands/test_purge.py
Labels: risk-review-ongoing, waiting-for-team

#1955 [CDF-24806] 😀 Hosted Extractor Job YAML
  cognite_toolkit/_cdf_tk/resource_classes/hosted_extractor_job.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_hosted_extractor_jobs.py
Labels: waiting-for-team

#1967 [CDF-24813] Pydantic class for Robotic data postprocessing
  cognite_toolkit/_cdf_tk/resource_classes/robotics/data_postprocessing.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_robotics/test_data_postprocessing.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-team

#1985 [CDF-25777] Made checksum a high-priority warning instead of throwing an error
  .vscode/launch.json
  cognite_toolkit/_cdf_tk/commands/modules.py
  tests/test_unit/test_cdf_tk/test_commands/test_modules.py
Labels: risk-review-ongoing, waiting-for-team

#1989 [prep CDF-25784] 👷 Remove asset migration cmd
  cognite_toolkit/_cdf_tk/apps/_migrate_app.py
  cognite_toolkit/_cdf_tk/commands/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/__init__.py
  cognite_toolkit/_cdf_tk/commands/_migrate/assets.py
  tests/test_integration/test_commands/test_migrate_assets.py
Labels: risk-review-ongoing, waiting-for-team

#2000 [CDF-25801] GraphQL YAML
  cognite_toolkit/_cdf_tk/builders/_datamodels.py
  cognite_toolkit/_cdf_tk/commands/_purge.py
  cognite_toolkit/_cdf_tk/commands/pull.py
  cognite_toolkit/_cdf_tk/cruds/__init__.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/__init__.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/datamodel.py
  cognite_toolkit/_cdf_tk/resource_classes/graphql_model.py
  tests/test_integration/test_commands/test_deploy.py
  tests/test_integration/test_commands/test_dump_data_model.py
  tests/test_unit/test_cdf_tk/test_cruds/test_data_model.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_graphql_model.py
  tests/test_unit/utils.py
Labels: risk-review-ongoing, waiting-for-team

#1992 [CDF-25767] 🔲 Migration results in terminal
  cognite_toolkit/_cdf_tk/commands/_migrate/command.py
  cognite_toolkit/_cdf_tk/utils/progress_tracker.py
  tests/test_unit/test_cdf_tk/test_utils/test_progress_tracker.py
Labels: risk-review-ongoing, waiting-for-team

#2004 [CDF-25816] 😅 Update to ResourceViewMapping
  cognite_toolkit/_cdf_tk/client/api/migration.py
  cognite_toolkit/_cdf_tk/client/data_classes/migration.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/_migrate/conversion.py
  cognite_toolkit/_cdf_tk/commands/_migrate/data_mapper.py
  cognite_toolkit/_cdf_tk/commands/_migrate/default_mappings.py
  cognite_toolkit/_cdf_tk/commands/_migrate/prepare.py
  cognite_toolkit/_cdf_tk/cruds/__init__.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/__init__.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/migration.py
  cognite_toolkit/_cdf_tk/utils/collection.py
  tests/data/complete_org_alpha_flags/modules/my_example_module/migration/default_asset.ResourceViewMapping.yaml
  tests/test_integration/test_toolkit_client/test_migration.py
  tests/test_unit/approval_client/config.py
  tests/test_unit/test_cdf_tk/test_client/test_resource_view_mapping.py
  tests/test_unit/test_cdf_tk/test_commands/test_migration.py
  tests/test_unit/test_cdf_tk/test_commands/test_migration_cmd/test_data_mapper.py
  tests/test_unit/test_cdf_tk/test_utils/test_collection.py
  tests/test_unit/test_cli/test_build_deploy_snapshots/complete_org_alpha_flags.yaml
Labels: risk-review-ongoing, waiting-for-team

#2012 [CDF-25588] Retreive multiple location filters with ids
  cognite_toolkit/_cdf_tk/client/api/location_filters.py
  tests/test_integration/test_toolkit_client/test_locations.py
Labels: risk-review-ongoing, waiting-for-team

#1972 [CDF-25737] Pydantic class for cognite file
  cognite_toolkit/_cdf_tk/resource_classes/cognitefile.py
  tests/test_unit/test_cdf_tk/test_resource_classes/test_cognitefile.py
Labels: risk-review-ongoing, waiting-for-team

#2019 [CDF-25840] 🧹 Remove view deployment recovery mechanism
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/datamodel.py
  cognite_toolkit/_cdf_tk/utils/tarjan.py
  tests/test_unit/test_cdf_tk/test_utils/test_tarjan.py
Labels: risk-review-ongoing, waiting-for-team

#2028 😠Rename to_directory_compatible
  cognite_toolkit/_cdf_tk/commands/_download.py
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  cognite_toolkit/_cdf_tk/cruds/_base_cruds.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/datamodel.py
  cognite_toolkit/_cdf_tk/cruds/_resource_cruds/workflow.py
  cognite_toolkit/_cdf_tk/storageio/_selectors.py
  cognite_toolkit/_cdf_tk/utils/__init__.py
  cognite_toolkit/_cdf_tk/utils/cdf.py
  cognite_toolkit/_cdf_tk/utils/file.py
  cognite_toolkit/_cdf_tk/utils/fileio/_writers.py
  cognite_toolkit/_cdf_tk/utils/table_writers.py
  tests/test_unit/test_cdf_tk/test_utils/test_file.py
Labels: risk-review-ongoing, waiting-for-team

#2025 [CDF-25754] minor annoyances in intro posters
  cognite_toolkit/_cdf_tk/apps/_core_app.py
  cognite_toolkit/_cdf_tk/commands/init.py
Labels: risk-review-ongoing, waiting-for-team

#2020 [CDF-25782] 🛁 Annotation mappings
  cognite_toolkit/_cdf_tk/commands/_migrate/default_mappings.py
Labels: risk-review-ongoing, waiting-for-team

#2024 [CDF-25835] ☔ Remove update_items from StorageIO
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/_migrate/adapter.py
  cognite_toolkit/_cdf_tk/commands/_migrate/command.py
  cognite_toolkit/_cdf_tk/commands/_upload.py
  cognite_toolkit/_cdf_tk/storageio/_applications.py
  cognite_toolkit/_cdf_tk/storageio/_asset_centric.py
  cognite_toolkit/_cdf_tk/storageio/_base.py
  cognite_toolkit/_cdf_tk/storageio/_instances.py
  cognite_toolkit/_cdf_tk/storageio/_raw.py
  tests/test_unit/test_cdf_tk/test_storageio/test_asset_centric.py
  tests/test_unit/test_cdf_tk/test_storageio/test_instance_io.py
  tests/test_unit/test_cdf_tk/test_storageio/test_raw.py
Labels: risk-review-ongoing, waiting-for-team
