Repository cognitedata/toolkit, pull requests merged in 2025-08, with the labels that each got.

#1797 [CDF-25329] 😄Auxiliary
  cognite_toolkit/_cdf_tk/utils/_auxiliary.py
  tests/test_unit/test_cdf_tk/test_utils/test_auxiliary.py
Labels: risk-review-ongoing, waiting-for-team

#1805 [CDF-25357] ☠ Add kill switch
  cognite_toolkit/_cdf_tk/utils/producer_worker.py
  tests/test_unit/test_cdf_tk/test_utils/test_producer_worker.py
Labels: waiting-for-team

#1812 [CDF-25387] 🤖 Publish agents issue
  cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readonly.group.yaml
  cognite_toolkit/_builtin_modules/common/cdf_auth_readwrite_all/auth/admin.readwrite.group.yaml
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/agent_loaders.py
  pyproject.toml
  tests/test_unit/test_cli/test_build_deploy_snapshots/cdf_auth_readwrite_all.yaml
  uv.lock
Labels: risk-review-ongoing, waiting-for-risk-review

#1816 [CDF-25393] 😅 GraphQL parser error
  cognite_toolkit/_cdf_tk/utils/graphql_parser.py
  tests/test_unit/test_cdf_tk/test_utils/test_graphql_parser.py
Labels: risk-review-ongoing, waiting-for-team

#1798 [CDF-25339] 🗜 FileIO compression
  cognite_toolkit/_cdf_tk/utils/fileio/__init__.py
  cognite_toolkit/_cdf_tk/utils/fileio/_compression.py
  tests/test_unit/test_cdf_tk/test_utils/test_fileio.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-team

#1819 [CDF-25405] Fix support dumping multiple groups
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  tests/test_unit/test_cdf_tk/test_commands/test_dump_resource.py
Labels: risk-review-ongoing, waiting-for-team

#1820 Clean up TestMigrateTimeSeriesCommand
  tests/test_integration/test_commands/test_migrate_timeseries.py
Labels: risk-review-ongoing, waiting-for-team

#1751 [CDF-25244] 🤛 Store metadata keys
  cognite_toolkit/_cdf_tk/commands/_profile.py
  tests/test_integration/test_commands/test_profile.py
Labels: risk-review-ongoing, waiting-for-team

#1824 [CDF-25266] 😅 Missing dependency
  cognite_toolkit/_cdf_tk/commands/build_cmd.py
  cognite_toolkit/_cdf_tk/tk_warnings/other.py
  tests/test_unit/test_cli/test_behavior.py
Labels: risk-review-ongoing, waiting-for-team

#1737 [CDF-25201] ⏩ HTTP processor
  cognite_toolkit/_cdf_tk/utils/auxiliary.py
  cognite_toolkit/_cdf_tk/utils/batch_processor.py
  tests/test_integration/test_utils/test_batch_processor.py
  tests/test_unit/conftest.py
  tests/test_unit/test_cdf_tk/test_client/conftest.py
  tests/test_unit/test_cdf_tk/test_utils/test_http_batch_processor.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-team

#1822 [CDF-25435] 🛑 Stop-gap solution solution to function queuing problem
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/client/api/extended_functions.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/function_loaders.py
  cognite_toolkit/_cdf_tk/utils/_auxiliary.py
  tests/test_integration/test_toolkit_client/test_extended_functions.py
  tests/test_unit/approval_client/config.py
  tests/test_unit/test_cdf_tk/test_client/test_extended_functions.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1783 [CDF-25320] 😊 Split batch processor
  cognite_toolkit/_cdf_tk/utils/batch_processor.py
  tests/test_integration/test_utils/test_batch_processor.py
  tests/test_unit/test_cdf_tk/test_utils/test_http_batch_processor.py
Labels: risk-review-ongoing, waiting-for-team

#1832 External library loading bugfix
  cognite_toolkit/_cdf_tk/commands/modules.py
  tests/test_unit/test_cdf_tk/test_commands/test_modules.py
Labels: risk-review-ongoing, waiting-for-team

#1843 [CDF-25530] 🦂 Chunk transformations
  cognite_toolkit/_cdf_tk/loaders/_resource_loaders/transformation_loaders.py
  tests/test_integration/test_loaders/test_resource_loaders.py
Labels: risk-review-ongoing, waiting-for-team

#1782 [CDF-25294] 🙃 Output file migration
  cognite_toolkit/_cdf_tk/client/_toolkit_client.py
  cognite_toolkit/_cdf_tk/commands/_migrate/assets.py
  tests/test_integration/test_commands/test_migrate_assets.py
  tests/test_integration/test_utils/test_batch_processor.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1851 [CDF-25554] 😅 Simplify migration mapping
  cognite_toolkit/_cdf_tk/commands/_migrate/assets.py
  cognite_toolkit/_cdf_tk/commands/_migrate/data_classes.py
  cognite_toolkit/_cdf_tk/commands/_migrate/files.py
  cognite_toolkit/_cdf_tk/commands/_migrate/timeseries.py
  tests/test_integration/test_commands/test_migrate_timeseries.py
  tests/test_unit/test_cdf_tk/test_commands/test_timeseries_migration.py
  tests/test_unit/test_cdf_tk/test_utils/test_collection.py
Labels: risk-review-ongoing, waiting-for-team

#1850 [CDF-25552]⛓️‍💥Support purge with unlink files
  cognite_toolkit/_cdf_tk/apps/_purge.py
  cognite_toolkit/_cdf_tk/client/testing.py
  cognite_toolkit/_cdf_tk/commands/_purge.py
  tests/test_unit/test_cdf_tk/test_commands/test_purge.py
Labels: risk-review-ongoing, waiting-for-team

#1858 🦑Tests concurrency issue
  tests/test_integration/test_toolkit_client/test_extended_files.py
Labels: risk-review-ongoing, waiting-for-team

#1849 [CDF-25202] 😛 Support dump functions
  cognite_toolkit/_cdf_tk/apps/_dump_app.py
  cognite_toolkit/_cdf_tk/commands/dump_resource.py
  tests/test_unit/test_cdf_tk/test_commands/test_dump_resource.py
Labels: risk-review-ongoing, waiting-for-team

#1855 [CDF-25543] 🖍 Convert string to DataType
  cognite_toolkit/_cdf_tk/utils/dtype_conversion.py
  cognite_toolkit/_cdf_tk/utils/fileio/_base.py
  cognite_toolkit/_cdf_tk/utils/useful_types.py
  tests/test_unit/test_cdf_tk/test_utils/test_dtype_conversion.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-team

#1871 👷Fix test
  tests/test_integration/test_commands/test_profile.py
  tests/test_integration/test_utils/test_aggregators.py
Labels: risk-review-ongoing, waiting-for-team

#1873 🐛Upload coverage report
  .github/workflows/release.yaml
Labels: risk-review-ongoing, waiting-for-team
